version: '2'
services:
  texlive:
    build:
      context: .
    volumes:
      - ./:/code:ro
      - ./slides:/code/slides
      - ./generated:/code/generated
      - ./justcode:/code/justcode
      - ./tmp:/code/tmp
