version: 2
jobs:
  test:
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - run: npm install -g makam
      - run: make test
  build:
    docker: &base-image
      - image: ablu/ubuntu-texlive-full
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apt-get install -y pandoc wamerican
      - run:
          name: Build everything
          command: make
      - store_artifacts:
          path: main.pdf
  artifact:
    docker:
      - image: node:9.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: make artifact
      - store_artifacts:
          path: artifact.tgz

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build
      - artifact:
          requires:
            - test
